name: 文書のリリース

on:
  push:
    tags:
      - v*

jobs:
  latex:
    name: LaTeX文書をコンパイル
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - run: sudo chown root /opt/homebrew/bin/gtar
      - run: sudo chmod u+s /opt/homebrew/bin/gtar
      - uses: actions/cache/restore@v4
        with:
          path: /usr/local/texlive
          key: 0
          enableCrossOsArchive: true
      - run: sudo /usr/local/texlive/2025/bin/universal-darwin/tlmgr path add
      - run: latexmk -lualatex test.tex
      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: test.pdf