name: 文書のリリース

on:
  push:
    tags:
      - v*

jobs:
  latex:
    name: LaTeX文書をコンパイル
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5
      - run: brew install basictex
      - run: sudo /usr/local/texlive/2025basic/bin/universal-darwin/tlmgr path add
      - run: sudo tlmgr update --self
      - run: sudo tlmgr install collection-langjapanese collection-latexextra collection-luatex latexmk tex-gyre-math
      - run: sudo tlmgr path add
      - run: latexmk -lualatex test.tex
      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: test.pdf