name: 文書のリリース

on:
  push:
    tags:
      - v*

jobs:
  latex:
    name: LaTeX文書をコンパイル
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5
      - id: cache
        uses: actions/cache/restore@v4
        with:
          path: texlive
          key: 0
          enableCrossOsArchive: true
      - run: brew install mactex-no-gui
      - run: texlive/2025/bin/universal-darwin/tlmgr path add
      - run: latexmk -lualatex test.tex
      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: test.pdf